theme: jekyll-theme-minimal
google_analytics: [UA-47865326-1]
title: [Kirø~$]
description: [IT consultant
<br/> 
Solver of problems
<br/> 
Board gamer and sci-fi fan
<br/> 
Ponderer of life mysteries
<br />
House owner and Handyman
]
