theme: jekyll-theme-minimal
google_analytics: [UA-47865326-1]
title: [Kirø~$]
description: [IT/DevOps consultant
<br/> 
Cloud/Solution Architect
<br/> 
Board gamer and sci-fi fan
<br/> 
Ponderer of life mysteries
<br />
House owner and Handyman
]
menu: [<ul>
            <li><a href="/terran">Terran</a><br/></li>
              <ul>
                <li>Black tea</li>
                <li>Green tea</li>
              </ul>
              <li><a href="https://linkedin.com/in/magnuskiro">CV - Linkedin</a></li>
          </ul>]
